---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
# Load the data
df <- read.csv("activity.csv")

# Transform the date into the Date format
df$date <- as.Date(df$date)
```

## What is mean total number of steps taken per day?
```{r}
# The total number of steps taken per day
total_steps_per_day <- tapply(df$steps, df$date, sum, na.rm = TRUE)

# The histogram of the total number of steps taken each day
hist(total_steps_per_day, main = "The Histogram of the Total Number of Steps Taken by Day", xlab = "Steps")

# The mean and median of the total number of steps taken per day
mean(total_steps_per_day)
median(total_steps_per_day)
```

## What is the average daily activity pattern?
```{r}
# A time series plot of the average number of steps taken (averaged across all days) versus the 5-minute intervals
average_steps_by_interval <- tapply(df$steps, df$interval, mean, na.rm=T)
plot(names(average_steps_by_interval), average_steps_by_interval, type="l", xlab = "Intervals", ylab = "Average Steps")

# Which 5-minute interval contains the maximum number of steps?
names(which.max(average_steps_by_interval))
```

## Imputing missing values
```{r}
# The total number of missing values in the dataset
nrow(df[is.na(df$steps),])

# Use the mean for that 5-minute interval to fill the missing values
x <- as.data.frame(average_steps_by_interval)
x <- cbind(row.names(x), x)
names(x) <- c("interval", "steps")

# Create a new dataset that is equal to the original dataset but with the missing data filled in.
new_df <- merge(df, x, by = "interval", all.x = T)
new_df[is.na(new_df$steps.x),"steps.x"] <- new_df[is.na(new_df$steps.x),"steps.y"]

# A histogram of the total number of steps taken each day
new_total_steps_per_day <- tapply(new_df$steps.x, new_df$date, sum, na.rm = TRUE)
hist(new_total_steps_per_day, main = "The Histogram of the Total Number of Steps Taken by Day", xlab = "Steps")

# The mean and median total number of steps taken per day.
mean(new_total_steps_per_day)
median(new_total_steps_per_day)

```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
# Create a new factor variable indicating whether a given date is a weekday or weekend day.
new_df$weekdays <- as.factor(weekdays(new_df$date)=="星期六" | weekdays(new_df$date)=="星期日")
levels(new_df$weekdays) <- c("weekday", "weekend")

# A panel plot containing a time series plot of the 5-minute interval and the average number of steps taken, averaged across all weekday days or weekend days.
par(mfrow= c(2,1), mar = c(4,4,1,0))
weekday_average_steps <- tapply(new_df[new_df$weekdays=="weekday","steps.x"], new_df[new_df$weekdays=="weekday", "interval"], mean, na.rm=T)
plot(names(weekday_average_steps), weekday_average_steps, type="l", xlab = "Average Steps", ylab = "weekday")

weekend_average_steps <- tapply(new_df[new_df$weekdays=="weekend","steps.x"], new_df[new_df$weekdays=="weekend", "interval"], mean, na.rm=T)
plot(names(weekend_average_steps), weekend_average_steps, type="l", xlab = "Average Steps", ylab = "weekend")

```
